[features]
resolution = true
skip-lint = false

[programs.localnet]
panenka_contest = "PANaGTE11111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
